### ISSUE TITLE
初始化 SDK 报错，Api 命名空间设置有误

### ISSUE THREAD

**Issue by DinnerWinnerSniper** [TencentCloudBase/tcb-manager-php#3]
![image](https://user-images.githubusercontent.com/51434435/59010801-1ceed780-8865-11e9-80a2-c44aab395931.png)

该目录下 Api.php 的命名空间被设置成 `namespace TcbManager`，实际应该为 `namespace TcbManager\Api`

目前执行
`TcbManager::init()`
初始化时会报 
`Class 'TcbManager\Api' not found in vendor\tencentcloudbase\tcb-manager-php\src\TcbManager.php:97`

**Comment by DinnerWinnerSniper** [comment]
https://github.com/TencentCloudBase/tcb-manager-php/blob/d2c529f00f6ca760fcfcb3abf324ea19ee5c3029/src/Version.php#L9

此处的常量未定义，应该写成字符串
const VERSION = "TENCENTCLOUD-CLIENT-PHP_v1.0.0";

**Comment by liuyanjie** [comment]
感谢反馈，已修复问题，版本 `^1.1.0`
